version: '3.8'

services:
  back:
    build: ./back
    container_name: back-app
    ports:
      - "8080:8080" 
    volumes:
      - ./back/src:/usr/src/app/src 
    environment:
      - NODE_ENV=development
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db
  front:
    build: ./front
    container_name: front-app
    ports:
      - "80:80" 
    volumes:
      - ./front/src:/usr/src/app/src
    environment:
      - REACT_APP_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=80
    depends_on:
      - back
  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopper
    ports:
      - "3306:3306" 
volumes:
  db_data:

